lib/hexo.js
As is noted on https://nodejs.org/api/process.html#process_process_exit_code
> In most situations, it is not actually necessary to call process.exit() explicitly.
It is problematic to print stdout and instruct process.exit() call. Now we set process.exitCode to allow the process exit naturally
=> fix(process): gracefully exit process

lib/hexo.js, package.json
If docs are included as a part of the primary application via yarn workspaces (See https://yarnpkg.com/lang/en/docs/workspaces/) the module resolution for the main `hexo` package fails, because it is nested above.
This PR addresses this issue by replacing the current custom module resolution with the [resolve](https://www.npmjs.com/package/resolve) which implements the resolve algorithm.
This, in my opinion, fits the design requirements as well as extending it to allow for the yarn workspace issue without much hassle.
=> Support Yarn Workspaces

.travis.yml, package.json
In the current setting of travis-ci, test target is v6 and stable.
Therefore, it can not be said that it actually supports the previous version.
So, you should explicitly write support version in package.json.
When this PR is applied, I plan to do semiautomatic refactoring using lebab, PR to upgrade each package, and so on.
=> Set support version of node.js explicitly as 6, 8, 9.

lib/console/init.js, package.json
[object-assign](https://www.npmjs.com/package/object-assign) is no longer maintained and it can be replace Object.assign
=> Use Object.assign instead of object-assign package

package.json, test/scripts/context.js, test/scripts/help.js
From (#32) PR.
Update sinon 6.3.5
The sinon has breaking change. So, this PR fix test case.
* [sinon.stub(object, method, func) is removed](https://sinonjs.org/guides/migrating-to-3.0). Use `callsFake` instead of it.
* [spy.reset is removed](https://sinonjs.org/guides/migrating-to-5.0). Use `resetHistory` instead of it.
=> Update sinon to 6.3.5

lib/console/init.js
This PR fixes an invalid type error that occurs while running `hexo init` with a numeric folder name.
E.g. Executing `hexo init 233` will produce the error as follows:
```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type number
at assertPath (path.js:39:11)
at Object.resolve (path.js:1088:7)
... (Omitted)
```
Since there'll be a need to create a new hexo project with numeric folder name in some cases, I've ensured that a string will be passed to the `resolve()` function.
=> Fixed the invalid type error while running init with a numeric folder name

package-lock.json, package.json
Following the issues with a dependency that broke hexo-cli, it seems indispensible to include package-lock.json
For other repository of hexojs project, it is less important, but for this project, it is indispensible, because user have no easy possibility to lock dependency to a specific version as this project is supposed to be installed globaly
For reference, see #49 and linked issues
=> update all packages to latest and include package-lock.json

lib/console/help.js
Expected:
```
$ hexo -h
Usage: hexo <command>
Commands:
help     Get help on a command.
init     Create a new Hexo folder.
version  Display version information.
Global Options:
--config  Specify config file instead of using _config.yml
--cwd     Specify the CWD
--debug   Display all verbose messages in the terminal
--draft   Display draft posts
--safe    Disable all plugins and scripts
--silent  Hide output on console
For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/
```
Actual:
```
$ hexo -h
Usage: hexo <command>
Commands:
help     Get help on a command.  init     Create a new Hexo folder.  version  Display version information.
Global Options:
--config  Specify config file instead of using _config.yml  --cwd …
```
=> fix(formatting): new lines

lib/console/init.js
- git:
- `--recursive` has been deprecated in git [2.13](https://www.git-scm.com/docs/git-clone/2.13.2), `--recurse-submodules` is available in git [2.3](https://www.git-scm.com/docs/git-clone/2.3.0) (possibly available in older version).
- `--depth=1` for shallow clone the hexo-starter, resulting in faster and smaller clone.
- yarn and npm:
- ignore optional dependencies
- Reduce verbosity for all commands.
from
```
$ hexo init
INFO  Cloning hexo-starter https://github.com/hexojs/hexo-starter.git
Cloning into 'test'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 14 (delta 0), reused 11 (delta 0), pack-reused 0
Unpacking objects: 100% (14/14), done.
Submodule 'themes/landscape' …
```
=> fix(init): shallow clone and reduce verbosity

lib/console/init.js, lib/hexo.js, test/scripts/init.js
[`HashStream()`](https://github.com/hexojs/hexo-util#hashstream) has been deprecated in favor of [`createSha1Hash()`](https://github.com/hexojs/hexo-util#createsha1hash)
=> refactor: destructure hexo-util

.mocharc.yml, test/mocha.opts
`mocha.opts` has been deprecated in [mocha v7](https://mochajs.org/#-opts-path).
=> test(mocha): use yml format

appveyor.yml
buggy in Node 14 and unnecessary.
=> ci(appveyor): stop updating npm

.gitignore, lib/console/init.js, lib/hexo.js, test/scripts/init.js
**What this PR does / why we need it:**
Fix `hexo init` bug with a number target name. Also ref #45 #199 .
**Special notes for your reviewer:**
/review 
@SukkaW @tommy351
=> fix(init): fix hexo init error with a number target project name

package-lock.json, package.json
`acorn` is introduced in #50. However, I don't see why the `acorn` is required.
Seeing the related issue, still don't know why acorn should be included in dependencies.
The PR shouldn't be merged before @tomap gives the explanation, in case the PR breaks something.
=> chore(deps): remove acorn

lib/console/init.js
this is helpful when running `$ hexo init custom-folder`.
=> fix(init): show where to run npm

lib/console/init.js
yarn 2 is not supported due to hexo's reliance on node_modules.
Package manager priority:
1. yarn
2. pnpm 
3. npm
=> feat(init): support pnpm and drop yarn 2

package-lock.json, package.json
https://github.com/hexojs/hexo-cli/pull/227
Other PRs only change package-lock which is not published.
=> release: 4.2.0

lib/hexo.js, test/scripts/version.js
Because cmd will be 'help' if do not specify the command. I think the modification enhances readability.
BTW, I added semicolon,which will be blocked by ESlint if missing.
=> refactor & style: let command default to be 'help'

.eslintignore, .eslintrc.json, .gitignore, lib/console/help.ts, lib/console/index.ts, lib/console/init.ts, lib/console/version.ts, lib/context.ts, lib/extend/console.ts, lib/find_pkg.ts, lib/goodbye.ts, lib/hexo.ts, package-lock.json, package.json, test/.eslintrc.json, test/index.js, test/scripts/context.js, test/scripts/find_pkg.js, test/scripts/help.js, test/scripts/hexo.js, test/scripts/init.js, test/scripts/version.js, tsconfig.json
There are some types missing in `hexo-fs` and `graceful-fs`. I'll work on the upstream first.
See https://github.com/hexojs/hexo-fs/pull/109
`"types"` in `package.json` may be incorrect
=> refactor: migrate typescript

lib/hexo.ts
fix hexojs/hexo#4334
when execute `hexo new`, both `path` and `slug` should have a string type
=> fix: path and slug should be string

package.json
- `prepublish` has been deprecated https://docs.npmjs.com/cli/v10/using-npm/scripts#prepare-and-prepublish
- repository key from string to object
=> chore: update deprecated `prepublish` and `repository` in `package.json`
